### ISSUE TITLE
👤 Olivier Nouguier 

### ISSUE THREAD

**Issue by cheleb** [Communautes-Montpellier/Code-de-conduite-slack-Communautes-Montpellier#4]
Votre nom sur le Slack: Olivier Nouguier

**Comment by cheleb** [comment]
Un des initiateurs du JUG, Canal "historique". Data/Soft Engineer chez Teads.

J'aime que les choses soient dites, la transparence, l'engagement et la loyauté.

1/ Liberté d'expression.
2/ Le droit à l'indifférence plus que le droit à la difference.
3/ Universaliste et jamais identitaire.

**Comment by HugoGresse** [comment]
Merci pour la candidature, vu que l'élection a été [reportée](https://comm-montpellier.slack.com/archives/C2M6NT1S5/p1605956741182900) je ferme l'issue. Durant ces élections, on a eu quelques discussion et j'ai demandé à Sophie de rejoindre la team admin en attendant de refaire des élections quand il y aura plus de candidats.
