### ISSUE TITLE
👤 Edouard COMTET

### ISSUE THREAD

**Issue by DarkIsDude** [Communautes-Montpellier/Code-de-conduite-slack-Communautes-Montpellier#5]
Bonjour. Je m'appelle Edouard COMTET et je suis sur Montpellier depuis maintenant 10ans.
Je suis développeur pour une entreprise espagnole (Hosco). Je suis donc en full remote et j'ai slack ouvert toute la journée.

Ce slack des communautés me permet de suivre l'actualité informatique (#rust) mais aussi de garder le contact et me tenir informé des meet-up. Ayant Slack ouvert toute la journée, c'est déjà un premier point.
Second point : cela fait un petit moment que je cherche à intégrer un peu plus la communauté tech sur Montpellier et aider à l'organisation des meetups, je pense que ceci peut-être un premier pas.

Votre nom sur le Slack: darkisdude

**Comment by HugoGresse** [comment]
Merci pour la candidature, vu que l'élection a été [reportée](https://comm-montpellier.slack.com/archives/C2M6NT1S5/p1605956741182900) je ferme l'issue. Durant ces élections, on a eu quelques discussion et j'ai demandé à Sophie de rejoindre la team admin en attendant de refaire des élections quand il y aura plus de candidats.
