### ISSUE TITLE
👤 Adrien Maret

### ISSUE THREAD

**Issue by Aschen** [Communautes-Montpellier/Code-de-conduite-slack-Communautes-Montpellier#6]
Très actif sur ce Slack depuis que je l'ai rejoint, je suis aussi sur d'autres communautés Slack (France-JS, Geekl.us, Lyon RB...) ainsi que sur Discord.
J'ai déjà été modo sur des forums (surtout sur Wow et Cs: source).

Je dois lire à peu près tous les messages qui tombent dans les canaux dont je fais partie. J'essaie déjà de faire respecter les règles du Slack aux newcomers etc

Sinon niveau pro je bosse sur Kuzzle, un produit complètement open source, et m'occupe déjà de la modération sur notre Discord qui compte 200 membres.

J'adore utiliser notre Slack pro, surtout les emojis :grin: :
![image](https://user-images.githubusercontent.com/4447392/99107040-7ecc7880-25e5-11eb-928f-b5f9e9a40f3f.png)

Votre nom sur le Slack: Adrien Maret

**Comment by HugoGresse** [comment]
Merci pour la candidature, vu que l'élection a été [reportée](https://comm-montpellier.slack.com/archives/C2M6NT1S5/p1605956741182900) je ferme l'issue. Durant ces élections, on a eu quelques discussion et j'ai demandé à Sophie de rejoindre la team admin en attendant de refaire des élections quand il y aura plus de candidats.
